### ISSUE TITLE
Cadastro de dívida

### ISSUE THREAD

**Issue by juliangutierrez** [smfazendaniteroi/sadp#4]
Código (6 números)

**Comment by juliangutierrez** [comment]
@larissascarvalho por favor coloque os campos de cadastro aqui. Obrigado!

**Comment by larissascarvalho** [comment]
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf2e999ff7f74001294b567/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65262b01f07a7587e72cef1a2307585f4fad445c0917ffa8da39baa47e21d40854b088270a36d43703adbf881eba05b8268f4886b2be8c4cc5fa70.png)

**Comment by luisfcosta2015** [comment]
@larissascarvalho esta parte está ok. Será que podemos ter mais atributos para o cadastro?
