### ISSUE TITLE
Ver com a Caixa cálculo da moeda

### ISSUE THREAD

**Issue by juliangutierrez** [smfazendaniteroi/sadp#46]

**Comment by larissascarvalho** [comment]
[email CAIXA pt1 - Disponibilização UPRD 01.02.2019.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf2e999ff7f74001294b567/125516c66e82c728ace21e0d46ed999b2a8ec38aaec08762e44de4c5690b67572017b3247e8ce121b34b6100acc8bd3f1e483a249e8d992ba7a83c72945e0becd87f4366867f4ef6edd15bad0ba825d91a86b7e9d81894e8352db18c8f4e3f1b014edafc0c66b285598a09a81fbe100cee467471ec6437744d951b71256b642ea9fed753838672e9.pdf)
