### ISSUE TITLE
Adicionar consulta aos índices do bndes

### ISSUE THREAD

**Issue by juliangutierrez** [smfazendaniteroi/sadp#61]

**Comment by larissascarvalho** [comment]
Seria interessante, que exista um histórico pelo menos da data da assinatura do contrato. No caso do PMAT do BNDES, a partir de 22/12/2014, ou seja, janeiro de 2015.

**Comment by juliangutierrez** [comment]
@larissascarvalho, não achei essa unidade monetária na listagem de moedas em https://www.bndes.gov.br/SiteBNDES/bndes/bndes_pt/Galerias/Convivencia/Moedas_Contratuais/lista_moedas.html

Tem algum link para acessar?

**Comment by larissascarvalho** [comment]
@juliangutierrez  nesse link que tu mandou, tem tanto a selic d2 (143) quanto a URTJLP (314)
